# Site settings
title: Dhrupad
email: sankrityayan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Classical North Indian temple and court music of the Dagar tradition
baseurl: "/q2" # the subpath of your site, e.g. /blog/
url: "http://sama66.github.io/" # the base hostname & protocol for your site
twitter_username: sanjaymaharishi
github_username:  sama66

# Build settings
markdown: kramdown
permalink: pretty
